// Generated from the Money Hub instrument list. s = Yahoo Finance symbol.
module.exports = [
  {"s":"BIL","type":"Bond","risk":"Low","region":"US","isin":"","name":"SPDR Bloomberg 1-3 Month T-Bill ETF","note":"Bond ETF · US T-bills (cash-like)"},
  {"s":"SHY","type":"Bond","risk":"Low","region":"US","isin":"","name":"iShares 1-3 Year Treasury Bond ETF","note":"Bond ETF · short US Treasuries"},
  {"s":"BND","type":"Bond","risk":"Low","region":"US","isin":"","name":"Vanguard Total Bond Market ETF","note":"Bond ETF · broad US bonds"},
  {"s":"AGG","type":"Bond","risk":"Low","region":"US","isin":"","name":"iShares Core US Aggregate Bond ETF","note":"Bond ETF · broad US bonds"},
  {"s":"BNDX","type":"Bond","risk":"Low","region":"US","isin":"","name":"Vanguard Total International Bond ETF","note":"Bond ETF · world ex-US bonds"},
  {"s":"LQD","type":"Bond","risk":"Medium","region":"US","isin":"","name":"iShares iBoxx $ Investment Grade Corporate Bond ETF","note":"Bond ETF · corporate bonds"},
  {"s":"TLT","type":"Bond","risk":"Medium","region":"US","isin":"","name":"iShares 20+ Year Treasury Bond ETF","note":"Bond ETF · long US Treasuries"},
  {"s":"EMB","type":"Bond","risk":"Medium","region":"US","isin":"","name":"iShares J.P. Morgan USD Emerging Markets Bond ETF","note":"Bond ETF · emerging-market bonds"},
  {"s":"HYG","type":"Bond","risk":"Medium","region":"US","isin":"","name":"iShares iBoxx $ High Yield Corporate Bond ETF","note":"Bond ETF · high-yield bonds"},
  {"s":"VOO","type":"ETF","risk":"Medium","region":"US","isin":"","name":"Vanguard S\u0026P 500 ETF","note":"500 largest US companies"},
  {"s":"VT","type":"ETF","risk":"Medium","region":"US","isin":"","name":"Vanguard Total World Stock ETF","note":"Whole-world stocks"},
  {"s":"SCHD","type":"ETF","risk":"Medium","region":"US","isin":"","name":"Schwab US Dividend Equity ETF","note":"US dividend payers"},
  {"s":"VYM","type":"ETF","risk":"Medium","region":"US","isin":"","name":"Vanguard High Dividend Yield ETF","note":"US high-dividend stocks"},
  {"s":"GLD","type":"ETF","risk":"Medium","region":"US","isin":"","name":"SPDR Gold Shares","note":"Physical gold"},
  {"s":"QQQ","type":"ETF","risk":"High","region":"US","isin":"","name":"Invesco QQQ Trust (Nasdaq-100)","note":"100 largest Nasdaq companies"},
  {"s":"VWO","type":"ETF","risk":"High","region":"US","isin":"","name":"Vanguard Emerging Markets ETF","note":"Emerging-market stocks"},
  {"s":"ARKK","type":"ETF","risk":"High","region":"US","isin":"","name":"ARK Innovation ETF","note":"Disruptive-tech growth"},
  {"s":"IBIT","type":"ETF","risk":"High","region":"US","isin":"","name":"iShares Bitcoin Trust ETF","note":"Bitcoin exposure"},
  {"s":"VWINX","type":"MF","risk":"Low","region":"US","isin":"","name":"Vanguard Wellesley Income Fund","note":"Mutual fund · income, bond-heavy"},
  {"s":"VBTLX","type":"Bond","risk":"Low","region":"US","isin":"","name":"Vanguard Total Bond Market Index Fund (Admiral)","note":"Bond mutual fund · US bonds"},
  {"s":"VWELX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Vanguard Wellington Fund","note":"Mutual fund · 65/35 stocks/bonds"},
  {"s":"PRWCX","type":"MF","risk":"Medium","region":"US","isin":"","name":"T. Rowe Price Capital Appreciation","note":"Mutual fund · balanced growth"},
  {"s":"FXAIX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Fidelity 500 Index Fund","note":"Mutual fund · S\u0026P 500"},
  {"s":"VFIAX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Vanguard 500 Index Fund (Admiral)","note":"Mutual fund · S\u0026P 500"},
  {"s":"VTSAX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Vanguard Total Stock Market Index (Admiral)","note":"Mutual fund · total US market"},
  {"s":"SWPPX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Schwab S\u0026P 500 Index Fund","note":"Mutual fund · S\u0026P 500"},
  {"s":"FZROX","type":"MF","risk":"Medium","region":"US","isin":"","name":"Fidelity ZERO Total Market Index Fund","note":"Mutual fund · 0% fee total market"},
  {"s":"FCNTX","type":"MF","risk":"High","region":"US","isin":"","name":"Fidelity Contrafund","note":"Mutual fund · large-cap growth"},
  {"s":"FBGRX","type":"MF","risk":"High","region":"US","isin":"","name":"Fidelity Blue Chip Growth Fund","note":"Mutual fund · growth stocks"},
  {"s":"AGTHX","type":"MF","risk":"High","region":"US","isin":"","name":"American Funds Growth Fund of America","note":"Mutual fund · growth stocks"},
  {"s":"JNJ","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Johnson \u0026 Johnson","note":"Healthcare · dividend payer"},
  {"s":"PG","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Procter \u0026 Gamble","note":"Consumer staples · dividend payer"},
  {"s":"KO","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Coca-Cola","note":"Consumer staples · dividend payer"},
  {"s":"BRK-B","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Berkshire Hathaway (B)","note":"Diversified conglomerate"},
  {"s":"JPM","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"JPMorgan Chase","note":"Banking"},
  {"s":"V","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Visa","note":"Payments"},
  {"s":"XOM","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"ExxonMobil","note":"Energy"},
  {"s":"MSFT","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Microsoft","note":"Software \u0026 cloud"},
  {"s":"AAPL","type":"Stock","risk":"Medium","region":"GL","isin":"","name":"Apple","note":"Consumer technology"},
  {"s":"SAP.DE","type":"Stock","risk":"Medium","region":"GL","isin":"DE0007164600","name":"SAP","note":"Enterprise software (Germany)"},
  {"s":"SIE.DE","type":"Stock","risk":"Medium","region":"GL","isin":"DE0007236101","name":"Siemens","note":"Industrial technology (Germany)"},
  {"s":"ALV.DE","type":"Stock","risk":"Medium","region":"GL","isin":"DE0008404005","name":"Allianz","note":"Insurance (Germany)"},
  {"s":"BMW.DE","type":"Stock","risk":"Medium","region":"GL","isin":"DE0005190003","name":"BMW","note":"Automotive (Germany)"},
  {"s":"MC.PA","type":"Stock","risk":"Medium","region":"GL","isin":"FR0000121014","name":"LVMH","note":"Luxury goods (France)"},
  {"s":"RMS.PA","type":"Stock","risk":"Medium","region":"GL","isin":"FR0000052292","name":"Hermès","note":"Luxury goods (France)"},
  {"s":"SU.PA","type":"Stock","risk":"Medium","region":"GL","isin":"FR0000121972","name":"Schneider Electric","note":"Electrical equipment (France)"},
  {"s":"NVDA","type":"Stock","risk":"High","region":"GL","isin":"","name":"NVIDIA","note":"AI chips"},
  {"s":"AMD","type":"Stock","risk":"High","region":"GL","isin":"","name":"Advanced Micro Devices","note":"Chips"},
  {"s":"AVGO","type":"Stock","risk":"High","region":"GL","isin":"","name":"Broadcom","note":"Chips \u0026 software"},
  {"s":"META","type":"Stock","risk":"High","region":"GL","isin":"","name":"Meta Platforms","note":"Social media \u0026 AI"},
  {"s":"AMZN","type":"Stock","risk":"High","region":"GL","isin":"","name":"Amazon","note":"E-commerce \u0026 cloud"},
  {"s":"GOOGL","type":"Stock","risk":"High","region":"GL","isin":"","name":"Alphabet (Google)","note":"Search, cloud \u0026 AI"},
  {"s":"TSLA","type":"Stock","risk":"High","region":"GL","isin":"","name":"Tesla","note":"Electric vehicles"},
  {"s":"PLTR","type":"Stock","risk":"High","region":"GL","isin":"","name":"Palantir","note":"Data analytics \u0026 AI"},
  {"s":"COIN","type":"Stock","risk":"High","region":"GL","isin":"","name":"Coinbase","note":"Crypto exchange"},
  {"s":"LLY","type":"Stock","risk":"High","region":"GL","isin":"","name":"Eli Lilly","note":"Pharma"},
  {"s":"ASML.AS","type":"Stock","risk":"High","region":"GL","isin":"NL0010273215","name":"ASML","note":"Chip equipment (Netherlands)"},
  {"s":"RHM.DE","type":"Stock","risk":"High","region":"GL","isin":"DE0007030009","name":"Rheinmetall","note":"Defence (Germany)"},
  {"s":"XEON.DE","type":"Bond","risk":"Low","region":"EU","isin":"LU0290358497","name":"Xtrackers EUR Overnight Rate Swap UCITS ETF","note":"Money market · near-cash, EUR"},
  {"s":"IBTA.L","type":"Bond","risk":"Low","region":"EU","isin":"IE00B3VWN179","name":"iShares $ Treasury Bond 1-3yr UCITS ETF","note":"Bond ETF · short US Treasuries"},
  {"s":"EUNH.DE","type":"Bond","risk":"Low","region":"EU","isin":"IE00B4WXJJ64","name":"iShares Core € Govt Bond UCITS ETF","note":"Bond ETF · euro government"},
  {"s":"VGEA.DE","type":"Bond","risk":"Low","region":"EU","isin":"IE00BH04GL39","name":"Vanguard EUR Eurozone Government Bond UCITS ETF","note":"Bond ETF · eurozone government"},
  {"s":"EUNA.DE","type":"Bond","risk":"Low","region":"EU","isin":"IE00BDBRDM35","name":"iShares Core Global Aggregate Bond EUR Hedged","note":"Bond ETF · global bonds, EUR hedged"},
  {"s":"EUN5.DE","type":"Bond","risk":"Medium","region":"EU","isin":"IE00B3F81R35","name":"iShares Core € Corp Bond UCITS ETF","note":"Bond ETF · euro corporate bonds"},
  {"s":"CBU0.L","type":"Bond","risk":"Medium","region":"EU","isin":"IE00B3VWN518","name":"iShares $ Treasury Bond 7-10yr UCITS ETF","note":"Bond ETF · medium US Treasuries"},
  {"s":"VWCE.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00BK5BQT80","name":"Vanguard FTSE All-World UCITS ETF (Acc)","note":"Whole-world stocks"},
  {"s":"VWRL.AS","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B3RBWM25","name":"Vanguard FTSE All-World UCITS ETF (Dist)","note":"Whole-world stocks, pays dividends"},
  {"s":"EUNL.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B4L5Y983","name":"iShares Core MSCI World UCITS ETF","note":"Developed-world stocks"},
  {"s":"XDWD.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00BJ0KDQ92","name":"Xtrackers MSCI World UCITS ETF","note":"Developed-world stocks"},
  {"s":"SPYY.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B44Z5B48","name":"SPDR MSCI All Country World UCITS ETF","note":"Whole-world stocks"},
  {"s":"SXR8.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B5BMR087","name":"iShares Core S\u0026P 500 UCITS ETF","note":"500 largest US companies"},
  {"s":"VUAA.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00BFMXXD54","name":"Vanguard S\u0026P 500 UCITS ETF (Acc)","note":"500 largest US companies"},
  {"s":"EXS1.DE","type":"ETF","risk":"Medium","region":"EU","isin":"DE0005933931","name":"iShares Core DAX UCITS ETF","note":"40 largest German companies"},
  {"s":"SXRT.DE","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B53L3W79","name":"iShares Core EURO STOXX 50 UCITS ETF","note":"50 leading eurozone companies"},
  {"s":"VHYL.AS","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B8GKDB10","name":"Vanguard FTSE All-World High Dividend Yield UCITS ETF","note":"Global dividend stocks"},
  {"s":"SGLD.L","type":"ETF","risk":"Medium","region":"EU","isin":"IE00B579F325","name":"Invesco Physical Gold ETC","note":"Physical gold"},
  {"s":"SXRV.DE","type":"ETF","risk":"High","region":"EU","isin":"IE00B53SZB19","name":"iShares NASDAQ 100 UCITS ETF","note":"100 largest Nasdaq companies"},
  {"s":"EXXT.DE","type":"ETF","risk":"High","region":"EU","isin":"DE000A0F5UF5","name":"iShares NASDAQ-100 UCITS ETF (DE)","note":"100 largest Nasdaq companies"},
  {"s":"IS3N.DE","type":"ETF","risk":"High","region":"EU","isin":"IE00BKM4GZ66","name":"iShares Core MSCI EM IMI UCITS ETF","note":"Emerging-market stocks"},
  {"s":"IUSN.DE","type":"ETF","risk":"High","region":"EU","isin":"IE00BF4RFH31","name":"iShares MSCI World Small Cap UCITS ETF","note":"Smaller companies worldwide"},
  {"s":"IQQH.DE","type":"ETF","risk":"High","region":"EU","isin":"IE00B1XNHC34","name":"iShares Global Clean Energy Transition UCITS ETF","note":"Clean-energy companies"},
  {"s":"0P00012I69.F","type":"Bond","risk":"Low","region":"EU","isin":"IE00B18GC888","name":"Vanguard Global Bond Index Fund EUR Hedged","note":"Bond mutual fund · global bonds"},
  {"s":"0P0000TKZG.L","type":"MF","risk":"Low","region":"EU","isin":"GB00B4NXY349","name":"Vanguard LifeStrategy 20% Equity Fund","note":"Mutual fund · 20% stocks / 80% bonds"},
  {"s":"0P0000TKZM.L","type":"MF","risk":"Medium","region":"EU","isin":"GB00B4PQW151","name":"Vanguard LifeStrategy 80% Equity Fund","note":"Mutual fund · 80% stocks / 20% bonds"},
  {"s":"0P0001CLDK.F","type":"MF","risk":"Medium","region":"EU","isin":"IE00BYX5NX33","name":"Fidelity MSCI World Index Fund","note":"Mutual fund · developed-world stocks"},
  {"s":"0P00000WLG.F","type":"MF","risk":"Medium","region":"EU","isin":"IE00B03HD191","name":"Vanguard Global Stock Index Fund","note":"Mutual fund · developed-world stocks"},
  {"s":"LU0072462426-USD.LU","type":"MF","risk":"Medium","region":"EU","isin":"LU0072462426","name":"BlackRock Global Allocation Fund","note":"Mutual fund · multi-asset"},
  {"s":"0P0000I5MD.F","type":"MF","risk":"Medium","region":"EU","isin":"LU0360483019","name":"Morgan Stanley Global Brands Fund","note":"Mutual fund · quality global stocks"},
  {"s":"0P00012I6A.F","type":"MF","risk":"High","region":"EU","isin":"IE0031786696","name":"Vanguard Emerging Markets Stock Index Fund","note":"Mutual fund · emerging markets"}
];
